DROP TABLE SALES_PLAN_SUMMARY;
DROP TABLE SALES_PLAN_DETAIL;
DROP TABLE SALES_PERFORMANCE_SUMMARY;
DROP TABLE SALES_PERFORMANCE_DETAIL;
DROP TABLE INVOICE;
DROP TABLE CUSTOMER_MST;
DROP TABLE BRANCH_MST;
