CREATE TABLE SALES_PLAN_SUMMARY (
    BRANCH_ID   VARCHAR2(6 CHAR) NOT NULL,
    YEAR    INTEGER ,
    MONTH   INTEGER ,
    AMOUNT  NUMERIC(10) NOT NULL,
    CONSTRAINT PK_SALPLES_PLAN_SUMMARY PRIMARY KEY (BRANCH_ID, YEAR, MONTH)
);

CREATE TABLE SALES_PLAN_DETAIL (
    BRANCH_ID   VARCHAR2(6 CHAR) NOT NULL,
    YEAR    INTEGER ,
    MONTH   INTEGER ,
    CUSTOMER_ID VARCHAR2(10 CHAR),
    AMOUNT  NUMERIC(10) NOT NULL,
    CONSTRAINT PK_SALPLES_PLAN_DETAIL PRIMARY KEY (BRANCH_ID, YEAR, MONTH, CUSTOMER_ID)
);

CREATE TABLE SALES_PERFORMANCE_SUMMARY (
    BRANCH_ID   VARCHAR2(6 CHAR) NOT NULL,
    YEAR    INTEGER ,
    MONTH   INTEGER ,
    AMOUNT  NUMERIC(10) NOT NULL,
    CONSTRAINT PK_SALPLES_PERFORMANCE_SUMMARY PRIMARY KEY (BRANCH_ID, YEAR, MONTH)
);

CREATE TABLE SALES_PERFORMANCE_DETAIL (
    BRANCH_ID   VARCHAR2(6 CHAR) NOT NULL,
    YEAR    INTEGER ,
    MONTH   INTEGER ,
    CUSTOMER_ID VARCHAR2(10 CHAR),
    AMOUNT  NUMERIC(10) NOT NULL,
    CONSTRAINT PK_SALPLES_PERFORMANCE_DETAIL PRIMARY KEY (BRANCH_ID, YEAR, MONTH, CUSTOMER_ID)
);

CREATE TABLE INVOICE (
    INVOICE_NO  VARCHAR2(20 CHAR) NOT NULL,
    INVOICE_DATE    DATE  NOT NULL,
    INVOICE_AMOUNT  NUMERIC(8)  NOT NULL,
    CUSTOMER_ID VARCHAR2(10 CHAR)  NOT NULL,
    CONSTRAINT PK_INVOICE PRIMARY KEY (INVOICE_NO)
);

CREATE TABLE CUSTOMER_MST (
    CUSTOMER_ID VARCHAR2(10 CHAR) NOT NULL,
    CUSTOMER_NAME   VARCHAR2(50 CHAR) NOT NULL,
    CUSTOMER_ADDRESS    VARCHAR2(200 CHAR) NOT NULL,
    CUSTOMER_TEL    VARCHAR2(11 CHAR) NOT NULL,
    CHARGE_BRANCH_ID    VARCHAR2(6 CHAR) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP ,
    CONSTRAINT PK_CUSTOMER_MST PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE BRANCH_MST (
    BRANCH_ID   VARCHAR2(10 CHAR) NOT NULL,
    BRANCH_NAME VARCHAR2(50 CHAR) NOT NULL,
    BRANCH_ADDRESS  VARCHAR2(200 CHAR) NOT NULL,
    BRANCH_TEL  VARCHAR2(11 CHAR) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP ,
    CONSTRAINT PK_BRANCH_MST PRIMARY KEY (BRANCH_ID)
);
