CREATE TABLE BATCH_JOB_REQUEST (
    JOB_SEQ_ID NUMBER GENERATED ALWAYS AS IDENTITY(MINVALUE 1 MAXVALUE 9223372036854775807 NOCYCLE) PRIMARY KEY,
    JOB_NAME VARCHAR2(100 CHAR) NOT NULL,
    JOB_PARAMETER VARCHAR2(200 CHAR),
    JOB_EXECUTION_ID NUMBER(19, 0),
    POLLING_STATUS VARCHAR2(10 CHAR) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP,
    PRIORITY INTEGER,
    GROUP_ID VARCHAR2(10 CHAR)
);
